#!/bin/bash
sudo apt update
sudo apt install tmux curl git wget -y
cd ~/healthscenarios
python3 -m venv venv
source venv/bin/activate
pip install ollama inputimeout
curl -fsSL https://ollama.com/install.sh | sh
ollama pull llama3.2:3b

curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
ln -s ~/.local/kitty.app/bin/kitty ~/.local/bin/
